/control/verbose 2
/run/verbose 2

#
#randomization control
#/random/setSeeds	1	1
#
#This is from TestEm9 20171019
#must be intiated before /run/initialize
#/testem/phys/addPhysics  emstandard
/testhadr/Physics QBBC
#set cut
#/cuts/setLowEdge 0.01 MeV
#
/run/initialize
#
/process/list
#
#/grdm/selectVolume Target
#/grdm/allVolumes
#

#
/run/printProgress 100
/run/beamOn 1000